mes-config-ms:
  commandes-last: 10  # Custom property to control last orders display

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commandes_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
