mes-config-ms:
  commandes-last: 10  # Example custom configuration

server:
  port: 8080  # Microservice runs on port 8080 (different from the Config Server)

management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh  # Enable Actuator endpoints

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
